--Create Requeired table--
CREATE TABLE IF NOT EXISTS modules(
  module_code VARCHAR(20) PRIMARY KEY,
  module_name VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS rights(
  right_code VARCHAR(20) PRIMARY KEY,
  module_code VARCHAR(20) REFERENCES modules(MODULE_code),
  description VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS user_rights(
  custno VARCHAR PRIMARY KEY REFERENCES customer(custno),
  CUST_VIEW SMALLINT    DEFAULT 0,
  CUST_ADD SMALLINT     DEFAULT 0,
  CUST_EDIT SMALLINT    DEFAULT 0,
  CUST_DEL SMALLINT     DEFAULT 0,
  SALES_VIEW SMALLINT   DEFAULT 0,
  SD_VIEW SMALLINT      DEFAULT 0,
  PROD_VIEW SMALLINT    DEFAULT 0,
  PRICE_VIEW SMALLINT   DEFAULT 0,
  ADM_USER SMALLINT     DEFAULT 0
);